version: "3"
services:
  data-notebook:
    build: .
    command: "start-notebook.sh"
    volumes:
      - ${WORKING_DIR}:/home/jovyan/work
      - ${DATASET_DIR}:/home/jovyan/datasets
    container_name: data_notebook
    ports:
      - 8888:8888
