version: "3"
services:
  data-notebook:
    #image: jupyter/pyspark-notebook:spark-3.3.2
    build: .
    #command: "start.sh jupyter lab --LabApp.token=''"
    command: "start-notebook.sh"
    volumes:
      - ${WORKING_DIR}:/home/jovyan/work
      - ${DATASET_DIR}:/home/jovyan/datasets
    container_name: data_notebook
    ports:
      - 8888:8888
